### ISSUE TITLE
Plugin doesn't work on Send-Only endpoints

### ISSUE THREAD

**Issue by timbussmann** [Particular/ServiceControl.Plugin.Nsb5.Heartbeat#11]
With release 2.0.0 of the Heartbeat Plugin, Send-Only endpoints are no longer working. This comes from switching to a `FeatureStartupTask` which are not started on Send-Only endpoints. An issue has been raised [here](https://github.com/Particular/NServiceBus/issues/2869) on the Core repository to change that behavior which would also support Send-Only endpoints again.

**Comment by SimonCropp** [comment]
how about we stop doing magic drop ins with assembly scanning and do an explicit api

**Comment by timbussmann** [comment]
@SimonCropp so no auto scanning for all Features then?

**Comment by DavidBoike** [comment]
Had a customer reiterate his need for heartbeats to work in send-only endpoints today. He relies upon the heartbeats to ensure that his send-only endpoints have a working RabbitMQ connection.

**Comment by johnsimons** [comment]
Fixed in #11

**Comment by timbussmann** [comment]
@johnsimons the link of the fix is this issue, can you provide the correct link to the fix?

**Comment by johnsimons** [comment]
Done @timbussmann
