### ISSUE TITLE
Allow heartbeats to be sent to multiple ServiceControl instances

### ISSUE THREAD

**Issue by marcselis** [Particular/ServiceControl.Plugin.Nsb5.Heartbeat#13]
In order to solve ServiceControl issue 684 (https://github.com/Particular/ServiceControl/issues/684) we need a way to send heartbeats to multiple ServiceControl instances.

I'll create a pull request with the proposed changes...

**Comment by johnsimons** [comment]
The real requirement is described in https://github.com/Particular/ServiceControl/issues/684#issuecomment-190444998

@Particular/servicecontrol-maintainers I think this can be closed  ?

**Comment by johnsimons** [comment]
@marcselis thanks a lot for the report, we appreciate the time you took to send us this.
However at this time this is not the direction we want to go, we understand a lot better your requirement and we now see how ServiceControl does not meet the requirement you describe in https://github.com/Particular/ServiceControl/issues/684#issuecomment-190444998.

So I am closing this for now, and hopefully we will be addressing this requirement some day.
