### ISSUE TITLE
Make TTL for heartbeat messages as a configurable option

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceControl.Plugin.Nsb5.Heartbeat#3]
When the plugin sends heartbeat messages, the TTL was fixed to four times the configured Heartbeat interval. In some cases, this still caused the heartbeat message to end up in the DLQ.

TTL is now configurable, same as the heartbeat interval.
Add the app setting in app.config as shown for either the `Interval` or `TTL` and provide the timespan string as the value. In this example, a heartbeat message will be sent every 30 seconds and the TTL for the heartbeat message is 2 minutes.

``` xml
  <appSettings>
    <add key="Heartbeat/Interval" value="00:00:30"/>
    <add key="Heartbeat/TTL" value="00:02:00"/>
  </appSettings>
```
## 

Relates to https://github.com/Particular/ServiceControl/issues/353

**Comment by cjoergensen** [comment]
@indualagarsamy Has this been released? I don't see it in the documentation page: http://docs.particular.net/servicecontrol/plugins/heartbeat#configuration

**Comment by indualagarsamy** [comment]
@cjoergensen - Apologies for the mix up. Yes, this was released as of 1.1.0. Not sure what happened with the labels. As you pointed out, I've updated the related documentation was for this as well.
You can find the release notes here (Most latest version is 2.0.0): https://github.com/Particular/ServiceControl.Plugin.Nsb5.Heartbeat/releases

**Comment by cjoergensen** [comment]
@indualagarsamy Awesome! Thanks!

**Comment by indualagarsamy** [comment]
@cjoergensen You are most welcome. Thanks so much for letting me know about the doco issue!
