### ISSUE TITLE
Machine Level Configuration

### ISSUE THREAD

**Issue by CraigKennedy** [Particular/ServiceControl.Plugin.Nsb5.Heartbeat#4]
It looks like you need the config section or for the convention to properly get the ServiceControl/Queue value. However, we are using the registry-based configuration option for the error/audit queues, so we didn't intend to have these values present in the config. Unfortunately, not having the sections in the config file seems to cause the service control heartbeat setup to fail.

Is there any way to use the same hierarchy used in the NServiceBus assembly (local config then registry if not found in the config file) so we can use the registry as a common configuration pattern for both the NServiceBus and the Heartbeat monitoring?

**Comment by DavidBoike** [comment]
Also affected: Desk case 11146

It comes down to this code:
https://github.com/Particular/ServiceControl.Plugin.Nsb5.Heartbeat/blob/master/src/ServiceControl.Plugin.Nsb5.Heartbeat/ServiceControlBackend.cs#L81-L119

If the ServiceControl/Queue appSetting is missing, then it tries to determine the machine name from the configured error queue. But the way it's checking for the MessageForwardingInCaseOfFaultConfig section completely ignores the possibility of a registry setting.

So without a MessageForwardingInCaseOfFaultConfig section in the app.config, it must assume localhost, and then it cannot verify the existence of that queue and fails.

**Comment by indualagarsamy** [comment]
Hi @DavidBoike @CraigKennedy 
Sorry about the delay on getting back on this. 
I think supplying values through the registry needs a high level discussion with the group to discuss the current pros and cons. 
For the time being, please use the config sections for now. 
@CraigKennedy - will that cause a problem for you or have you already moved to this model? Thanks much.

**Comment by CraigKennedy** [comment]
I am fine for the time being.  My main thought behind the request is the desire to use Configuration Management (chef in our case) to control the Service Control queue.  We already do this for the error queue (set the registry value to the central error/audit queue) and control this via Config Management as server admin rather than redeploying/tokenizing values between release tiers.

**Comment by indualagarsamy** [comment]
@CraigKennedy - Thanks for your input. I will raise this with the team and see how we can move forward on this.

**Comment by johnsimons** [comment]
Hi @CraigKennedy,

At this stage we are not going to fix this.
The workaround is to have chef pull those values from the machine registry and populate the config appsettings, see http://docs.particular.net/servicecontrol/plugins/#connecting-to-servicecontrol
