### ISSUE TITLE
ObjectDisposedException raised due to Heartbeat feature initialization

### ISSUE THREAD

**Issue by danielmarbach** [Particular/ServiceControl.Plugin.Nsb5.Heartbeat#5]
## Who's affected
Everybody using Heartbeat plugins and starting the endpoint while the service control queue is not available.

## Symptoms
1. Remove Service Control Queue or restrict access
2. Add Heartbeat plugin to host
3. Start the host
4. `ObjectDisposedException` is raised which hides the actual root cause which is `This endpoint is unable to contact the ServiceControl Backend to report endpoint information`

## Analysis
Because the ctor of the `ServiceControlBackend` does verify if the SC is running properly and instead of blowing up it is calling `CriticalErrorAction` the bus is asynchronously shut down (and therefore the `CommonObjectBuilder` is disposed and because the exception is not thrown to the caller the bus continuous to create the `IWantToRunWhenConfigurationIsComplete`.
the next one in the enumerable is the featuresupport starter which tries to access the `CommonObjectBuilder` which then throws a `ObjectDisposedException`

My 2cents as a design hint:
* `CriticalErrorAction` should only be used when the Backend Component was already running and it loses connection during runtime
* The first intial check in the `ctor` should throw an exception and not call `CriticalErrorAction`
* Food for thought: We should talk about an important design rule which I follow all the time: object can be constructed without triggering behavior. Therefore I would suggest to introduce an `Initialize` or `Start` method on the `ServiceControlBackend` which checks the availability of the backend.

@indualagarsamy If you agree I can send a pull. Should we also check V4?

**Comment by indualagarsamy** [comment]
@danielmarbach - pretty sure it'll be the same in v4 and v3. 
I agree on throwing an exception on startup (as there's no way the e/p can communicate if the queue isn't there even after 2 mins :) )

**Comment by indualagarsamy** [comment]
@danielmarbach - Self hosting or not, in both cases, the log message do contain the queue not found exception as well. Which makes the problem a little less severe. While I agree that the overall exception reported is misleading, i think we should update the issue description.

**Comment by lnu** [comment]
Just got it this morning. The message is not meaningful.
It means also that anybody who want to work locally need the ServiceControl installed?

**Comment by danielmarbach** [comment]
@lnu You don't need ServiceControl installed but you need to have the destination queue setup (in case of MSMQTransport)

**Comment by lnu** [comment]
I understand but it means that if you don't install ServiceControl  you have to create the queue manually.

**Comment by johnsimons** [comment]
@danielmarbach I am with @lnu, I think we should create the local queue if it doesn't exist.
We do this only in "debug mode", thoughts ?

**Comment by danielmarbach** [comment]
We can do this when we move it to a feature and a startup task fo vnext. Ok?
>
>

-- 

Daniel Marbach

Solution Architect, Particular Software

Email:  daniel.marbach@particular.net

Web:    www.particular.net
<http://t.signauxneuf.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4RzDjlVS9QB88pTc_dW3Ljg7x56dWyBdgBXs402?t=http%3A%2F%2Fwww.particular.net%2F&si=4896787407044608&pi=33cc6202-1f31-4040-8d6c-e70641f44bba>

**Comment by lnu** [comment]
Seems good!

**Comment by danielmarbach** [comment]
Just stumbled over this again. I had a customer code with customized assembly scanning. Because my endpoint assembly name was different then the customers it didn't scan the provided

    public class ErrorQueue : IProvideConfiguration<MessageForwardingInCaseOfFaultConfig>
    {
        public MessageForwardingInCaseOfFaultConfig GetConfiguration()
        {
            return new MessageForwardingInCaseOfFaultConfig { ErrorQueue = "error" };
        }
    }

    public class AuditQueue : IProvideConfiguration<AuditConfig>
    {
        public AuditConfig GetConfiguration()
        {
            return new AuditConfig { QueueName = "audit" };
        }
    }

This made the following method not returning anything

https://github.com/Particular/ServiceControl.Plugin.Nsb5.Heartbeat/blob/master/src/ServiceControl.Plugin.Nsb5.Heartbeat/ServiceControlBackend.cs#L111

Therefore the service control backend address could not be determined and was `null`. Sending to a null address never works of course

https://github.com/Particular/ServiceControl.Plugin.Nsb5.Heartbeat/blob/master/src/ServiceControl.Plugin.Nsb5.Heartbeat/ServiceControlBackend.cs#L142

Which then shuts down the bus.

**Comment by timbussmann** [comment]
@danielmarbach @indualagarsamy @andreasohlund 
should we check if the queue exists at all at startup? 
* We currently don't do that with other queues (e.g. Forwarding queue).
* see the issue with this (merged) PR: https://github.com/Particular/ServiceControl.Plugin.Nsb5.Heartbeat/pull/8
Endpoints wouldn't start up at all if the queue / network (e.g. SQL server, remote machine) isn't available at the moment.

**Comment by andreasohlund** [comment]
>We currently don't do that with other queues (e.g. Forwarding queue).

True , but we do have plans to do this, we discussed this in https://github.com/Particular/PlatformDevelopment/issues/394

>  Endpoints wouldn't start up at all if the queue / network (e.g. SQL server, remote machine) isn't available at the moment.

We guide users to set their windows services to restart when failing to start so that should cover most of this but I do see your point. Isn't the question if we see the heartbeats to be critical for operating the endpoint safely or not?

If yes we leave the current code. If no we should probably remove it and also the circuit breaker?

**Comment by timbussmann** [comment]
the queue creation is still in discussion. I think the issue (PR) is an interesting scenario to consider for this topic.

all I'm saying is, that there is an inconsistency about handling unavailable queues where the plugins are even more strict than the core.

**Comment by andreasohlund** [comment]
Thinking this through I think we should remove the startup check and also the circuit breaker and just log errors.

Problems with heartbeats will be detected and remedied since the Ops person won't see the instance as green in SP. (thanks @SimonCropp for beeing my rubber duck)

**Comment by andreasohlund** [comment]
If we go with this we need to rev the major version since this is a breaking change

**Comment by indualagarsamy** [comment]
@andreasohlund - I think the whole reason for the endpoint circuit breaker is that, if you've gone to the headaches of adding the plugin to your endpoint, you want this to be monitored and if there's any reason that it can't be monitored, then you know it right away. For Ops, service not starting is an easier thing to see than a service running and not issuing heartbeats. From a debugging standpoint, you see the endpoint running and not show up in the dashboard and the first thing you look is, is the heartbeat dll in there and the service is running? Logs will tell you I suppose as an after the fact. We are relying on Ops guys to look at the dashboard to determine endpoint heartbeat is not working or not. In  some places I've worked, Ops don't actively monitor the dashboard and it might be a while before they realize heartbeats aren't working. @gbiellem - your thoughts on this?

@timbussmann - As far as checking the queues on startup, SC could be running on a different machine and the audit / error queues could be pointing to a remote machine? How far do we think of validating?

**Comment by timbussmann** [comment]
@indualagarsamy probably depends if we'd do the validation on a transport level or not. there are a lot of open questions.

it just seems strange that failing to send heartbeats, which shouldn't be mission critical, can shutdown the endpoint while other, more important(?), parts don't do that on failures.

Should it be configurable if you want the endpoint to fail or not?

**Comment by indualagarsamy** [comment]
@timbussmann - what more important parts don't do shutdown on failure? Can you elaborate?

**Comment by timbussmann** [comment]
@indualagarsamy all messages we want to send during message processing I'd say

**Comment by indualagarsamy** [comment]
@timbussmann - If an endpoint is trying to send a message to a queue that doesn't exist, then the host will throw an exception. Essentially the queues specified in the endpoint message mappings should exist. In that regard, the heartbeat plugin behavior is right?

**Comment by andreasohlund** [comment]
Let's play with the tought that we switch to http calls for the heartbeats (since a queue doesn't give us much here) would we then kill the endpoint if SC can't be contacted?

To me it boils down to asking the users the question: 

"Would you want keep on processing messages even if the heartbeats are missconfigured/not working in some way?" 

I'd say the answer is yes since the hearbeats isn't needed to safely operate the endpoint. This seems like the safe for production default since problems with heartsbeats will be deteced in SP anyway and Ops will start investigating it without us killing the endpoint.

Thoughts?

**Comment by timbussmann** [comment]
@indualagarsamy shouldn't that message go to FLR->SLR->Errorq?

I think Andreas has some very good points.

**Comment by a-belevich** [comment]
Our SQL Transport is quite similar to HTTP in the example, because it's running on remote box. So, when we encounter connectivity problems, or SQL Server box restarts - all endpoints become dead in 2 minutes. In our development environments this "when" happens almost every night, and I'm not sure how it would work in production.

I'd say that decision whether and when to kill an endpoint is important and environment-specific. Somebody wants to rely on SC notifications, and somebody needs services to stop. So, I'd say user should be able to configure these aspects: whether to kill endpoint, and how long it should take.

**Comment by indualagarsamy** [comment]
@andreasohlund - I think this assumption is incorrect:
> I'd say the answer is yes since the hearbeats isn't needed to safely operate the endpoint. This seems like the safe for production default since problems with heartsbeats will be deteced in SP anyway and Ops will start investigating it without us killing the endpoint.

You're assuming that Ops will monitor SP anyway. Ops may not be actively monitoring the SP dashboard and they may not be aware of the endpoint being down at all (as the service is running). When the e/p is shutdown, the service is stopped and typically Ops has other mechanisms to alert them when services stop running, which will cause them to act, which will then cause them to have a look at the SP dashboard and then go on from there.

**Comment by timbussmann** [comment]
Not everyone is using multiple monitoring tools. Have the requirement to have a second monitoring tool in order to see endpoints shut down by the first monitoring tool doesn't sound very intuitive.

Making it configurable would definitely put the user in control of the behavior and we could avoid the breaking change. But I'm not sure if there is a real demand for the circuit breaker, so I think we also should avoid code no one is going to use and has to be maintained. As for general we should have a clear concept for all Plugins on how to deal with exceptions. What about deprecating the circuitbreaker behavior and see if someone responds to that?

**Comment by andreasohlund** [comment]
>You're assuming that Ops will monitor SP anyway. Ops may not be actively monitoring the SP dashboard and they may not be aware of the endpoint being down at all (as the service is running). 

So you're saying that Ops don't care about the heartbeats, since they are not looking at SP, but they still want to kill the endpoint and cause a production outage becase of said heartbeats?

This doesn't make sense to me

**Comment by indualagarsamy** [comment]
@andreasohlund @timbussmann @a-belevich 
Given that we have a way for Ops to get notified for hearbeat failure, 
http://docs.particular.net/servicepulse/custom-notification-and-alerting-using-servicecontrol-events#custom-notification-and-alerting-using-servicecontrol-events-alerting-on-heartbeatstopped-event

I am good with not stopping the endpoint on heartbeat failure. My concern is mitigated by the fact that Ops can still get alerts and react, while the endpoint continues to run.

**Comment by gbiellem** [comment]
@andreasohlund 

>Let's play with the tought that we switch to http calls for the heartbeats (since a queue doesn't give us much here) would we then kill the endpoint if SC can't be contacted?

Why HTTP?

> Not everyone is using multiple monitoring tools. Have the requirement to have a second monitoring tool in order to see endpoints shut down by the first monitoring tool doesn't sound very intuitive.

We could use SNMP for heartbeats and then this would open them up to be consumed directly from other monitoring tools not just ServiceControl

**Comment by andreasohlund** [comment]
>Why HTTP?

No reason, just used that as an example of a more unreliable way of talking to SC.

>We could use SNMP for heartbeats and then this would open them up to be consumed directly from other monitoring tools not just ServiceControl

+1, my only point was that using the queuing system doesn't really give us anything so alternate ways should be investigated.

I assume that you agree that we shouldn't kill the endpoint should there be issues emmiting the heartbeats?

**Comment by gbiellem** [comment]
> I assume that you agree that we shouldn't kill the endpoint should there be issues emmiting the heartbeats?

Definitely!

**Comment by andreasohlund** [comment]
Awesome, @timbussmann bombs away!

**Comment by timbussmann** [comment]
![refactoring](http://www.isanet.org/Portals/0/Users/108/00/33900/stranglovebombride.jpg)

@andreasohlund @indualagarsamy 
seems like I forgot about the `RegisterEndpointStartup` message which is sent on initialization. Even when removing the Queue check it will still fail and kill the endpoint currently. After the discussion on this issue I think the best approach would be to not start sending heartbeats and retry registering after a minute. As soon the registration was successful we can start sending heartbeats.

**Comment by andreasohlund** [comment]
Yes that makes sense!

Perhaps just move it to a `IWantToRunAtStartup` ?

**Comment by indualagarsamy** [comment]
@timbussmann - yes that makes sense to me. 
@andreasohlund - how will that work on a send-only endpoint? i.e. moving it to a IWantToRunWhenBusStartsAndStops. Does Start get invoked for send-only endpoints? I don't think it does.

**Comment by andreasohlund** [comment]
Good catch Indu, that won't fly. We need to kick off a new thread for the retries then? Or just try once to send the RegisterEndpointStarted message. If we fail we just log and proceed?

**Comment by indualagarsamy** [comment]
I like the back off and try a few times approach and then logging a final, I give up. That can resolve temporary hiccups.  I don't think we need to optimize on validating if queue exists, as it gets dicey once you start validating remote queues. See John Breakwell's article: http://blogs.msdn.com/b/johnbreakwell/archive/2008/07/31/checking-if-msmq-queues-exist-is-hard-work-so-should-you-bother.aspx

**Comment by johnsimons** [comment]
Reading the original description of the report, it seems the issue was that the original error message is becoming tangled in an `ObjectDisposedException`, hence the reason for this issue.

As I see it we have 2 audiences here, we have:

1. the developer running nsb locally on their machine;
1. the ops;

Could the answer to this issue be a a mix of both ? Would it be fair to say that 1. doesn't really care about it but 2. does care and fail fast makes sense ?

Does this observation make sense ?

**Comment by andreasohlund** [comment]
>2. does care and fail fast makes sense ?

Don't agree, as I said in https://github.com/Particular/ServiceControl.Plugin.Nsb5.Heartbeat/issues/5#issuecomment-134136945 my opinion is that no one want this to kill the endpoint since that would cause a production outage

**Comment by gbiellem** [comment]
I agree with @andreasohlund here, a failure with monitoring shouldn't kill the endpoint

**Comment by indualagarsamy** [comment]
@johnsimons - for the ops, we do have the notifications via SC. That should help serve Ops while the e/p still handles messages.

**Comment by timbussmann** [comment]
should we create a new issue in order for release 2.0?
